### PR TITLE
watch for changes and dynamically update module list

### PR DESCRIPTION
**Pull request by stdavis**
No idea why the tests aren't passing on windows. If you run them you'll see they fail on comparing strings that look exactly the same to me. I tried for a bit but don't feel like it's worth my time. Otherwise I think that this is ready to go.

### CODE REVIEW

**Comment by stdavis** [comment]
Waiting on this bug to be fixed for App Veyor tests to pass: https://github.com/atom/atom/issues/9277

**Comment by Arcanemagus** [comment]
Btw, you might want to start using the Windows Atom installer, now that there is a stable link to the latest installer. Chocolaty is installing v1.0.9 for you, which is very out of date.

For an example configuration see [here](https://github.com/atom/ci/pull/12/files).

**Comment by stdavis** [comment]
Thanks, @Arcanemagus! I'll check it out.

**Comment by stdavis** [comment]
@steveoh Not sure if you want to review this or not. We are still waiting for atom/atom#9277 to be fixed with atom 1.3 but I think that we can just manually check to see if all of the tests pass in the interim. I'd like to get this branch merged. I've been running it on my machine for a while and it seems to work well.

**Comment by steveoh** [comment]
worked on windows for me after deleting the node_modules folder. I say try it. :shipit:

**Pull request merged**
